import { ClientEvent, ServerEvent } from './enums';
import {
  answerAcceptedEventSchema,
  answerProgressEventSchema,
  answerWindowOpenEventSchema,
  gameEndEventSchema,
  gamePausedEventSchema,
  gameResumedEventSchema,
  gameStartingEventSchema,
  hostTransferredEventSchema,
  joinLobbyPayloadSchema,
  lobbyStateSchema,
  nextRoundCountdownEventSchema,
  reactionEventSchema,
  reactionPayloadSchema,
  reactionWindowEventSchema,
  roomClosedEventSchema,
  roomSettingsSchema,
  roundEndEventSchema,
  roundStartEventSchema,
  setPlayerInfoPayloadSchema,
  setReadyPayloadSchema,
  submitAnswerPayloadSchema,
  timerTickEventSchema,
  wsErrorEventSchema,
} from './schemas';

export const clientEventSchemas = {
  [ClientEvent.JOIN_LOBBY]: joinLobbyPayloadSchema,
  [ClientEvent.SET_PLAYER_INFO]: setPlayerInfoPayloadSchema,
  [ClientEvent.SET_READY]: setReadyPayloadSchema,
  [ClientEvent.SEND_REACTION]: reactionPayloadSchema,
  [ClientEvent.SUBMIT_ANSWER]: submitAnswerPayloadSchema,
  [ClientEvent.START_GAME]: undefined,
  [ClientEvent.PAUSE_GAME]: undefined,
  [ClientEvent.RESUME_GAME]: undefined,
  [ClientEvent.END_GAME]: undefined,
  [ClientEvent.RESTART_GAME]: undefined,
  [ClientEvent.CHOOSE_NEXT_QUIZ]: undefined,
  [ClientEvent.HIDE_QR]: undefined,
} as const;

export const serverEventSchemas = {
  [ServerEvent.LOBBY_STATE]: lobbyStateSchema,
  [ServerEvent.PLAYER_JOINED]: lobbyStateSchema,
  [ServerEvent.PLAYER_LEFT]: lobbyStateSchema,
  [ServerEvent.PLAYER_UPDATED]: lobbyStateSchema,
  [ServerEvent.REACTION_RECEIVED]: reactionEventSchema,
  [ServerEvent.HOST_TRANSFERRED]: hostTransferredEventSchema,
  [ServerEvent.GAME_STARTING]: gameStartingEventSchema,
  [ServerEvent.ROUND_START]: roundStartEventSchema,
  [ServerEvent.ANSWER_WINDOW_OPEN]: answerWindowOpenEventSchema,
  [ServerEvent.TIMER_TICK]: timerTickEventSchema,
  [ServerEvent.ANSWER_ACCEPTED]: answerAcceptedEventSchema,
  [ServerEvent.ANSWER_PROGRESS]: answerProgressEventSchema,
  [ServerEvent.ROUND_END]: roundEndEventSchema,
  [ServerEvent.REACTION_WINDOW_OPEN]: reactionWindowEventSchema,
  [ServerEvent.REACTION_WINDOW_CLOSED]: undefined,
  [ServerEvent.NEXT_ROUND_COUNTDOWN]: nextRoundCountdownEventSchema,
  [ServerEvent.GAME_END]: gameEndEventSchema,
  [ServerEvent.GAME_PAUSED]: gamePausedEventSchema,
  [ServerEvent.GAME_RESUMED]: gameResumedEventSchema,
  [ServerEvent.ROOM_CLOSED]: roomClosedEventSchema,
  [ServerEvent.ROOM_SETTINGS_UPDATED]: roomSettingsSchema,
  [ServerEvent.ERROR]: wsErrorEventSchema,
} as const;
